file[Git-CommitData-chenge] bug fix.

diff --git a/git-shell/Git-CommitDate-chenge b/git-shell/Git-CommitDate-chenge
--- a/git-shell/Git-CommitDate-chenge
+++ b/git-shell/Git-CommitDate-chenge
@@ -24,19 +24,15 @@ select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'; do
         timezone="+0900"
         new_date="$week $month $date $time $year $timezone"
         export GIT_COMMITTER_DATE="$new_date"
+        export GIT_AUTHOR_DATE="$new_date"
         current_message=$(git log -1 --pretty=%B)
-        if git diff-index --quiet HEAD --; then
-            echo "No changes to commit."
+        git commit --amend --no-edit --date="$new_date"
+        if [ $? -eq 0 ]; then
+            git rebase HEAD~1 --committer-date-is-author-date
+            git log --pretty=fuller
         else
-            git add .
-            git commit --amend --no-edit --date="$new_date"
-            if [ $? -eq 0 ]; then
-                git rebase HEAD~1 --committer-date-is-author-date
-                git log --pretty=fuller
-            else
-                echo "Failed to amend the commit."
-                exit 1
-            fi
+            echo "Failed to amend the commit."
+            exit 1
         fi
         break
     done
