file[Git-CommitDate-chenge] bug fix.

diff --git a/git-shell/Git-CommitDate-chenge b/git-shell/Git-CommitDate-chenge
--- a/git-shell/Git-CommitDate-chenge
+++ b/git-shell/Git-CommitDate-chenge
@@ -1,6 +1,5 @@
 #!/bin/bash
 ESC=$(printf '\033')
-
 PS3="${ESC}[1;39mWeek > ${ESC}[m"
 select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'; do
     echo "${ESC}[1;35mSelected > $week${ESC}[m"
@@ -9,7 +8,6 @@ select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'; do
         echo "Invalid date format."
         exit 1
     fi
-
     PS3="${ESC}[1;39mMonth > ${ESC}[m"
     select month in 'Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Nov' 'Dec'; do
         echo "${ESC}[1;35mSelected > $month${ESC}[m"
@@ -18,39 +16,29 @@ select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'; do
             echo "Invalid year format."
             exit 1
         fi
-
         read -p "${ESC}[1;39mPress set time (format HH:MM:SS) : ${ESC}[m" time
         if [[ ! $time =~ ^([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$ ]]; then
             echo "Invalid time format."
             exit 1
         fi
-
         timezone="+0900"
         new_date="$week $month $date $time $year $timezone"
         export GIT_COMMITTER_DATE="$new_date"
-
         current_message=$(git log -1 --pretty=%B)
-
         if git diff-index --quiet HEAD --; then
             echo "No changes to commit."
         else
-            git commit -am "$current_message"
-            if [ $? -ne 0 ]; then
-                echo "Failed to commit changes."
+            git add .
+            git commit --amend --no-edit --date="$new_date"
+            if [ $? -eq 0 ]; then
+                git rebase HEAD~1 --committer-date-is-author-date
+                git log --pretty=fuller
+            else
+                echo "Failed to amend the commit."
                 exit 1
             fi
-        fi
-
-        git commit --amend --no-edit --date="$new_date"
-        if [ $? -eq 0 ]; then
-            git rebase HEAD~1 --committer-date-is-author-date
-            git log --pretty=fuller
-        else
-            echo "Failed to amend the commit."
-            exit 1
         fi
         break
     done
     break
 done
-
