file[Git-CommitDate-chenge]

diff --git a/git-shell/Git-CommitDate-chenge b/git-shell/Git-CommitDate-chenge
--- a/git-shell/Git-CommitDate-chenge
+++ b/git-shell/Git-CommitDate-chenge
@@ -1,30 +1,42 @@
 #!/bin/bash
 ESC=$(printf '\033')
 
-PS3="${ESC}[1;39mweek > ${ESC}[m"
-select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'
-do
+PS3="${ESC}[1;39mWeek > ${ESC}[m"
+select week in 'Mon' 'Tue' 'Wed' 'Thu' 'Fri' 'Sat' 'Sun'; do
+    echo "${ESC}[1;35mSelected > $week${ESC}[m"
+    read -p "${ESC}[1;39mPress set date (format DD) : ${ESC}[m" date
+    if [[ ! $date =~ ^[0-9]{1,2}$ ]]; then
+        echo "Invalid date format."
+        exit 1
+    fi
 
-	echo "${ESC}[1;35mselected > $week${ESC}[m"
-	read -p "${ESC}[1;39mPress set date : ${ESC}[m" date
-	printf "${ESC}[1;35mEntered date > $date${ESC}[m\n"
+    PS3="${ESC}[1;39mMonth > ${ESC}[m"
+    select month in 'Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Nov' 'Dec'; do
+        echo "${ESC}[1;35mSelected > $month${ESC}[m"
+        read -p "${ESC}[1;39mPress set year (format YYYY) : ${ESC}[m" year
+        if [[ ! $year =~ ^[0-9]{4}$ ]]; then
+            echo "Invalid year format."
+            exit 1
+        fi
 
-	PS3="${ESC}[1;39mmonth > ${ESC}[m"
+        read -p "${ESC}[1;39mPress set time (format HH:MM:SS) : ${ESC}[m" time
+        if [[ ! $time =~ ^([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$ ]]; then
+            echo "Invalid time format."
+            exit 1
+        fi
 
-	select month in 'Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Nov' 'Dec'
-	do
-		echo "${ESC}[1;35mselected > $month${ESC}[m"
+        timezone="+0900"  # 日本の標準時間
 
-		printf "${ESC}[1;35mEntered month > $month${ESC}[m\n"
-		read -p "${ESC}[1;39mPress set year (format yyyy) : ${ESC}[m" year
-		printf "${ESC}[1;35mEntered year > $year${ESC}[m\n"
-		read -p "${ESC}[1;39mPress set time (format HH:MM:SS) : ${ESC}[m" time
-		printf "${ESC}[1;35mEntered time > $time${ESC}[m\n"
-
-		git commit --amend --date="$week $month $date $time $year +0900"
-		git rebase HEAD~1 --committer-date-is-author-date
-		git log --pretty=fuller
-		break
-	done
-	break
+        git commit --amend --date="$week $month $date $time $year $timezone"
+        if [ $? -eq 0 ]; then
+            git rebase HEAD~1 --committer-date-is-author-date
+            git log --pretty=fuller
+        else
+            echo "Failed to amend the commit."
+            exit 1
+        fi
+        break
+    done
+    break
 done
+
